name: Kubernetes Minicube Integration Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kubernetes-launch:
    runs-on: "linux.20_04.16x"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          set -eux
          pip install -e .[kubernetes]
      - name: Start Kubernetes
        run: |
          scripts/setup_minikube.sh
      - name: Run Kubernetes Integration Tests
        env:
          INTEGRATION_TEST_STORAGE: ${{ secrets.INTEGRATION_TEST_STORAGE }}
          CONTAINER_REPO: localhost:5000/torchx
        run: |
          chmod +x scripts/minicube_trainer.py
          scripts/minicube_trainer.py
