name: Slurm Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slurm:
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Configure AWS
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          if [ -n "$AWS_ROLE_ARN" ]; then
            export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
            export AWS_DEFAULT_REGION=us-west-2

            echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
            echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
            echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

            curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          fi
      - name: Install Dependencies
        run:
          set -ex

          pip install wheel ec2instanceconnectcli
      - name: Run Slurm Integration Tests
        env:
          SLURM_INSTANCE_MASTER: ${{ secrets.SLURM_INSTANCE_MASTER }}
          SLURM_KNOWN_HOST: ${{ secrets.SLURM_KNOWN_HOST }}
        run: |
          set -e

          mkdir -p ~/.ssh
          echo "$SLURM_KNOWN_HOST" >> ~/.ssh/known_hosts

          scripts/slurmint.sh
